### ISSUE TITLE
大佬能不能来几个动漫站的配置

### ISSUE THREAD

**Issue by zhibufan** [lovebeefcat/movie-bot-conf#5]
跪求动漫花园，冬樱，天雪，谢谢大佬

**Comment by zhibufan** [comment]
动漫花园 dmhy.org
天雪 www.skyey2.com

**Comment by lovebeefcat** [comment]
这几个站和蜜柑对比有没有特殊优势？

**Comment by zhibufan** [comment]
天雪是有独家自购的有原盘，冬樱基本是搬动漫花园的pt

**Comment by lovebeefcat** [comment]
那可以考虑安排一下啊

**Comment by zhibufan** [comment]
谢谢大佬，wintersakura.net这个是冬樱，前两个天雪是长期开放注册的，dmhy不用注册
